/**
 * @file product-category.types.ts
 * @module modules/product-categories
 *
 * @description
 * TypeScript domain types for the Product Categories feature.
 *
 * DOMAIN LAYER vs REPOSITORY LAYER
 * ----------------------------------
 * The repository layer (`product-categories.repository.ts`) defines `ProductCategoryRow`,
 * which mirrors the exact database column structure. This file defines the
 * DOMAIN types that the rest of the application (hooks, pages, components)
 * should work with. In practice they are nearly identical, but separating
 * them means:
 *  - Repository types can change without breaking the UI contract
 *  - Client-specific computed fields could be added here without touching the DB
 *
 * INTERFACES IN THIS FILE
 * -----------------------
 * ProductCategory          → Read: what you get back from the server
 * CreateProductCategoryInput → Write: what you send to create a new one
 * UpdateProductCategoryInput → Write: what you send to update an existing one
 */

/**
 * Represents a product category as used throughout the application UI.
 * All fields come from the `product_categories` database table.
 */
export interface ProductCategory {
  /** UUID primary key generated by the database */
  id: string;
  /** Human-readable category name, e.g. "Electronics" */
  name: string;
  /** Whether this category is currently visible/selectable in the UI */
  is_active: boolean;
  /** Soft-delete flag. True means the record is hidden (never hard-deleted) */
  is_deleted: boolean;
  /** ISO 8601 timestamp of when this record was created */
  created_at: string;
  /** ISO 8601 timestamp of the last update (managed by a DB trigger) */
  updated_at: string;
}

/**
 * Input shape for creating a new product category.
 * Only `name` is required — all other fields (is_active, timestamps, id)
 * are handled by the database.
 */
export interface CreateProductCategoryInput {
  name: string;
}

/**
 * Input shape for updating an existing product category.
 * Both fields are optional (PATCH semantics) — supply only what needs to change.
 *
 * Example: `{ is_active: false }` to deactivate without renaming.
 */
export interface UpdateProductCategoryInput {
  name?: string;
  is_active?: boolean;
}
