export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  DASHBOARD: '/dashboard',
  DASHBOARD_CUSTOMERS: '/dashboard/customers',
  DASHBOARD_CUSTOMERS_NEW: '/dashboard/customers/new',
  DASHBOARD_SUBJECTS: '/dashboard/subjects',
  DASHBOARD_SUBJECTS_NEW: '/dashboard/subjects/new',
  DASHBOARD_SUBJECTS_DETAIL: (id: string) => `/dashboard/subjects/${id}`,
  DASHBOARD_SUBJECTS_EDIT: (id: string) => `/dashboard/subjects/${id}/edit`,
  DASHBOARD_ATTENDANCE: '/dashboard/attendance',
  DASHBOARD_SERVICE_CATEGORIES: '/dashboard/service/categories',
  DASHBOARD_SERVICE_BRANDS: '/dashboard/service/brands',
  DASHBOARD_SERVICE_BRAND_DETAIL: (id: string) => `/dashboard/service/brands/${id}`,
  DASHBOARD_SERVICE_DEALERS: '/dashboard/service/dealers',
  DASHBOARD_SERVICE_DEALER_DETAIL: (id: string) => `/dashboard/service/dealers/${id}`, 
  DASHBOARD_INVENTORY: '/dashboard/inventory',
  DASHBOARD_TEAM: '/dashboard/team',
  DASHBOARD_TEAM_DETAIL: (id: string) => `/dashboard/team/${id}`,
  DASHBOARD_TECHNICIAN: '/dashboard',
} as const;
